
project_id = "ewzsiiclccdhszlbqzex"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
api_port = 54325

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
additional_redirect_urls = ["https://ewzsiiclccdhszlbqzex.supabase.co"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_anonymous_sign_ins = false

[edge-runtime]
policy = "per_worker"
inspector_port = 8083
